### ISSUE TITLE
Support Cordova 12 / Android 12

### ISSUE THREAD

**Issue by yasinkocak** [Scandit/scandit-cordova-datacapture-core#3]
To build a new APK with API Level 33 required minimum Gradle version 7.5. But this cordova plugin is targetted on Gradle 7.4.2 and it's not compatible to build APK with API Level 33

**Comment by ScanditSupport** [comment]
Hi @yasinkocak

Thank you for reporting that. 

We're already looking into it and checking possible solutions for this. 

If you want us to inform you about the progress, please get in contact with us directly via: [Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
