### ISSUE TITLE
Error after reloading

### ISSUE THREAD

**Issue by fabienwnklr** [Scandit/scandit-cordova-datacapture-core#7]
hello,

i've found an error in my app, when i reloading app an error occured

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Settings')`

src : https://github.com/Scandit/scandit-cordova-datacapture-core/blob/master/www/js/Camera%2BRelated.js#L111

> [!IMPORTANT]
> if i close and open app , no error... only with reload..

it's rather embarrassing and blocking cause i reload my app for disconnect user..

thanks !

**Comment by ScanditSupport** [comment]
Hi @fabienwnklr 

this seems to be an error with our API not being exposed properly in your app after reloading. 

Can you please reach out to us directly and share a few snippets of your code on how you implemented Scandit?

[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by fabienwnklr** [comment]
Thanks for reply,

i reproduce with this sample : https://github.com/Scandit/datacapture-cordova-samples/blob/master/BarcodeCaptureSimpleSample/template_src/www/index.js

my code isn't called on reaload, snippet :

```js
// Create data capture context using your license key.
const context = Scandit.DataCaptureContext.forLicenseKey(appKey);

// Use the world-facing (back) camera and set it as the frame source of the context. The camera is off by
// default and must be turned on to start streaming frames to the data capture context for recognition.
window.camera = Scandit.Camera.default;
context.setFrameSource(window.camera);

// The barcode capturing process is configured through barcode capture settings
// and are then applied to the barcode capture instance that manages barcode recognition.
const settings = new Scandit.BarcodeCaptureSettings();

// The settings instance initially has all types of barcodes (symbologies) disabled. For the purpose of this
// sample we enable the QR symbology. In your own app ensure that you only enable the symbologies that your app
// requires as every additional enabled symbology has an impact on processing times.
settings.enableSymbologies([
    Scandit.Symbology.QR,
    Scandit.Symbology.MicroQR,
    Scandit.Symbology.DataMatrix,
]);

// Create new barcode capture mode with the settings from above.
window.barcodeCapture = Scandit.BarcodeCapture.forContext(context, settings);

// Register a listener to get informed whenever a new barcode got recognized.
barcodeCapture.addListener({
    didScan: (barcodeCapture, session, _) => {
        const barcode = session.newlyRecognizedBarcodes[0];
        const symbology = new Scandit.SymbologyDescription(barcode.symbology);

        if (!barcode.data) {
            window.overlay.brush = Scandit.Brush.transparent;
            return;
        }

        window.overlay.brush = new Scandit.Brush(
            Scandit.Color.fromHex("FFF0"),
            Scandit.Color.fromHex("FFFF"),
            3
        );

        qrCodeProcess(barcode.data, coldefmod.IDGEO);
        barcodeCapture.isEnabled = false;
        camera.switchToDesiredState(Scandit.FrameSourceState.Off);
        document.getElementById("data-capture-view").hidden = true;
    },
});

// To visualize the on-going barcode capturing process on screen, setup a data capture view that renders the
// camera preview. The view must be connected to the data capture context.
const view = Scandit.DataCaptureView.forContext(context);

// Connect the data capture view to the HTML element, so it can fill up its size and follow its position.
view.connectToElement(document.getElementById("data-capture-view"));

// Add a barcode capture overlay to the data capture view to render the location of captured barcodes on top of
// the video preview. This is optional, but recommended for better visual feedback.
window.overlay = Scandit.BarcodeCaptureOverlay.withBarcodeCaptureForViewWithStyle(
    barcodeCapture,
    view,
    Scandit.BarcodeCaptureOverlayStyle.Frame
);
window.overlay.viewfinder = new Scandit.RectangularViewfinder(
    Scandit.RectangularViewfinderStyle.Square,
    Scandit.RectangularViewfinderLineStyle.Light
);

camera.switchToDesiredState(Scandit.FrameSourceState.On);
barcodeCapture.isEnabled = true;
```

**Comment by ScanditSupport** [comment]
Hi @fabienwnklr 

Thank you for sharing more details. 

Please try to use the latest production release [6.20.0](https://www.npmjs.com/package/scandit-cordova-datacapture-barcode/v/6.20.0) as we introduced some improvements and you shouldn't experience this anymore. 

In case you still have troubles with reloading, please reach out directly to us: 

[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)

**Comment by fabienwnklr** [comment]
Okay, i don't have error anymore.. 

Sorry, i should have done this first before creating this issue..

Thank you for your response!

**Comment by ScanditSupport** [comment]
Hi @fabienwnklr 

Glad to hear that! Thank you for the heads up. 

In case any further doubts arise, please feel free to reach out to us directly. 
[Submit a request – Frequently Asked Questions (FAQ)](https://support.scandit.com/hc/en-us/requests/new)
